### ISSUE TITLE
Regression has happened to x86 version of VIPS binaries after 8.7.4

### ISSUE THREAD

**Issue by Megadino** [libvips/build-win64-mxe#9] opened 2019-10-14 08:47 UTC
It seems something has happened with x86 binaries when version was raised from 8.7.4 to 8.8.0

VIPS that is bundled in all **vips-dev-w32-all-8.8.X.zip** packages can not initialize at all, and hangs forever on call:

`return Vips.Init("NetVips") == 0;`

with high CPU utilization. Looks like it is stuck in infinite cycle. 
Tested and it appears on both Windows 10(64) and Windows 7(64).

Version **vips-dev-w32-all-8.7.4.zip** works fine.
Version **vips-dev-w64-all-8.8.3.zip** works fine.

**Comment by kleisauke** [comment] 2019-10-21 17:36
I suspect this could be a DLL load issue,  as I couldn't reproduce this with NetVips 1.1.0 and:
- vips-dev-w32-all-8.8.3.zip
- vips-dev-w32-web-8.8.3.zip
- vips-dev-w64-all-8.8.3.zip
- vips-dev-w64-web-8.8.3.zip
- [NetVips.Native.win-x64](https://www.nuget.org/packages/NetVips.Native.win-x64/)
- [NetVips.Native.win-x86](https://www.nuget.org/packages/NetVips.Native.win-x86/)

(the releases are always tested on the NetVips test suite before they are published).

Perhaps it picks up the old (v8.7.4) dependencies?

Tips to solve DLL load issues:
- Try to reorder your PATH environment variable so that the `vips` bin directory (for e.g. `C:\vips-dev-8.8\bin`) is included first.
- Try to test with `vips.exe` outside the `bin` directory, for example:
   ```bash
   vips copy x.jpg x.png
   ````
   If it'll throw any error, the wrong DLLs are being loaded.
- Use the [`Dependencies`](https://lucasg.github.io/Dependencies/) program to check if all dependencies can be found and if they are picked up from the correct location. See for example:
![dependencies](https://user-images.githubusercontent.com/12746591/67227668-fb6b4280-f437-11e9-99e8-ff0ca8c94284.png)

**Comment by Megadino** [comment] 2020-01-23 19:27
Figured out it's because of Visual Studio. When a project is being ran from Visual Studio, and Visual Studio is attached as a debugger - then the library hangs on 
 `return Vips.Init("NetVips") == 0;`

This is reproducible on Windows 7 and 10, using Visual Studio 2017 and Visual Studio 2019. 
If to run a project as a regular .EXE process without attached Visual Studio it works fine.

**Comment by kleisauke** [comment] 2020-04-14 20:35
Sorry, this fell off my radar. It looks like this was caused by GLib: https://gitlab.gnome.org/GNOME/glib/-/issues/2025

I've updated GLib to 2.64.1 with https://github.com/libvips/build-win64-mxe/commit/65e1a6d44a3afa551f4835bdab1c67f2c12e5785, you can test these binaries here: 
https://github.com/libvips/build-win64-mxe/releases/tag/v8.9.1-static

Thanks for reporting this! This update will be included in the forthcoming NetVips.Native release.

**Comment by kleisauke** [comment] 2020-04-28 13:38
[NetVips.Native v8.9.2](https://www.nuget.org/packages/NetVips.Native/8.9.2) is now available.

I'll close this issue for now, please feel free to re-open if there's still a problem.

**Closed by kleisauke** 2020-04-28 13:38 UTC
Labels: bug
